// Generated by CoffeeScript 1.10.0
var API;

API = (function() {
  function API(sender, api) {
    var r;
    r = new Reqs({
      send: sender,
      SPI: api
    });
    return r;
  }

  return API;

})();

//# sourceMappingURL=api.js.map
