// Generated by CoffeeScript 1.10.0
var Main;

Main = (function() {
  var connect, createApi;

  createApi = function() {
    return new Reqs({
      send: function(d) {
        if (APP.WS.readyState === 1) {
          APP.WS.send(d);
        }
      },
      server: {
        screen: function() {
          if (this.cb) {
            this.cb(window.outerWidth, window.outerHeight);
          }
        }
      },
      client: {
        ping: function(pingxt) {
          pingxt(Date.now(), function(ping1, time) {
            var ping2;
            ping2 = Date.now() - time;
            console.log('ping to server:', ping1, '/ ping from server:', ping2, '/ total:', ping1 + ping2);
          });
        }
      }
    });
  };

  connect = function(obj) {
    var reconnectTimer;
    reconnectTimer = null;
    return new WS({
      host: 'localhost',
      port: 10001,
      open: function(e) {
        obj.WS = this;
        API.build();
      },
      msg: function(e) {
        API.parse(e.data);
      },
      error: function(e) {},
      close: function(e) {
        if (reconnectTimer) {
          clearInterval(reconnectTimer);
        }
        reconnectTimer = setTimeout(function() {
          return connect(obj);
        }, 3000);
      }
    });
  };

  function Main() {
    window.API = createApi();
    connect(APP);
    console.log('Welcome to Reqs example!\nType:\n    API.client.ping()\nOr:\n    API.client.callScreen()\nThen check server console messages and Network:ws tab in browser to see details. Library in develop and this just basic example.');
  }

  $(Main);

  return Main;

})();

//# sourceMappingURL=main.js.map
