// Generated by CoffeeScript 1.10.0
var Main;

Main = (function() {
  var apiList, connect, createApi;

  apiList = {
    test: function(a, b) {
      console.log('Test return from server:', a, b);
    }
  };

  createApi = function() {
    return new API(function(d) {
      if (APP.WS.readyState === 1) {
        APP.WS.send(d);
      }
    }, apiList);
  };

  connect = function(obj) {
    var reconnectTimer;
    console.log('Connecting...');
    reconnectTimer = null;
    return new WS({
      host: 'localhost',
      port: 10001,
      open: function(e) {
        obj.WS = this;
        console.log('Connected');
      },
      msg: function(e) {
        APP.API.parse(e.data);
      },
      error: function(e) {},
      close: function(e) {
        if (reconnectTimer) {
          clearInterval(reconnectTimer);
        }
        reconnectTimer = setTimeout(function() {
          return connect(obj);
        }, 3000);
      }
    });
  };

  function Main() {
    $window = $(window); $body = $(window.body);
    var api;
    APP.API = api = createApi();
    connect(APP);
  }

  $(Main);

  return Main;

})();

//# sourceMappingURL=main.js.map
