// Generated by CoffeeScript 1.10.0
var $body, $window, APP, getRandomInt, id, noop, toBoolean, toFloat, toInt;

$window = $();

$body = $();

id = {};

APP = {};

noop = function() {};

(function(exports) {
  var t;
  t = Object.prototype.toString;
  exports.isNumber = function(s) {
    return s === s && (t.call(s) === '[object Number]');
  };
  exports.isString = function(s) {
    return t.call(s) === '[object String]';
  };
  exports.isArray = function(s) {
    return t.call(s) === '[object Array]';
  };
  exports.isObject = function(s) {
    return t.call(s) === '[object Object]';
  };
  exports.isFunction = function(s) {
    return t.call(s) === '[object Function]';
  };
  exports.isBoolean = function(s) {
    return t.call(s) === '[object Boolean]';
  };
  exports.isType = function(s, t) {
    return t.call(s).slice(8, -1) === t;
  };
  exports.type = function(s) {
    return t.call(s).slice(8, -1);
  };
})(this);

Date.prototype.timeNow = function() {
  return ((this.getHours() < 10)?"0":"") + this.getHours() +":"+ ((this.getMinutes() < 10)?"0":"") + this.getMinutes() +":"+ ((this.getSeconds() < 10)?"0":"") + this.getSeconds();
};

getRandomInt = function(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
};

toBoolean = function(v) {
  return !(v === 'false' || v === '0' || v === 'null' || v === '' || v === 0 || v === null || v === false || v === void 0 || v !== v);
};

toInt = function(v) {
  return parseInt(v, 10) || 0;
};

toFloat = function(v) {
  return parseFloat(v, 10) || 0;
};

//# sourceMappingURL=vars.js.map
